### PR TITLE
Upgrade to Tika 1.9

### PR DESCRIPTION
**Pull request by jipis**
This will solve the problem found in issue #31 by upgrading to the most recent version of Tika.

### CODE REVIEW

**Comment by rojotek** [comment]
@Erol it would be awesome to see this merged in :)

**Comment by jipis** [comment]
@Erol, so, can we get this pull request merged?

**Comment by rojotek** [comment]
@jipis do you think it's worth upgrading to tika 1.10? @Erol what do you think about merging this in?

**Comment by jasonperrone** [comment]
Did @Erol  pass away or something? How can we get Tika upgraded?

**Comment by Erol** [comment]
@jasonperrone I'm very much alive, thank you. Just been very busy. My apologies if this took too long to get merged.

**Comment by jasonperrone** [comment]
LOL. Glad you're alive, Erol :)

So, I actually ended up forking your project and upgrading Tika all the way to 1.11. And guess what? It didn't help the PDF parsing at all. So, I switched to PDF Reader.

**Pull request merged**
